ekf_filter_node:
  ros__parameters:

    frequency: 30.0

    sensor_timeout: 0.2

    two_d_mode: true

    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # ==========================================
    # Wheel odometry
    # ==========================================

    odom0: /wheel_odom

    # State order:
    #
    # x, y, z,
    # roll, pitch, yaw,
    # vx, vy, vz,
    # vroll, vpitch, vyaw,
    # ax, ay, az
    #
    # Use wheel:
    # vx
    # vy
    #
    # Do NOT use encoder yaw rate initially.
    # We trust BNO085 gyro more for rotation.

    odom0_config: [
      false, false, false,
      false, false, false,
      true,  true,  false,
      false, false, false,
      false, false, false
    ]

    odom0_differential: false
    odom0_relative: false

    # ==========================================
    # BNO085
    # ==========================================

    imu0: /imu/data

    # Initially use ONLY angular velocity Z.
    #
    # We will add BNO085 absolute yaw after
    # handling its mounting transform properly.

    imu0_config: [
      false, false, false,
      false, false, false,
      false, false, false,
      false, false, true,
      false, false, false
    ]

    imu0_differential: false
    imu0_relative: false

    # BNO085 linear acceleration is not being
    # fused in this first version.

    imu0_remove_gravitational_acceleration: true
