ekf_filter_node:
  ros__parameters:

    frequency: 30.0
    sensor_timeout: 0.2

    two_d_mode: true

    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # ==========================================
    # Mecanum wheel odometry
    # ==========================================

    odom0: /wheel_odom

    # State:
    # x y z
    # roll pitch yaw
    # vx vy vz
    # vroll vpitch vyaw
    # ax ay az
    #
    # Use encoder Vx and Vy only.

    odom0_config: [
      false, false, false,
      false, false, false,
      true,  true,  false,
      false, false, false,
      false, false, false
    ]

    odom0_differential: false
    odom0_relative: false

    # ==========================================
    # BNO085
    # ==========================================

    imu0: /imu/data

    # For now use only gyro Z.
    #
    # Do NOT fuse the BNO085 quaternion yet.
    # We'll add absolute heading after this
    # basic EKF passes our rotation tests.

    imu0_config: [
      false, false, false,
      false, false, false,
      false, false, false,
      false, false, true,
      false, false, false
    ]

    imu0_differential: false
    imu0_relative: false

    imu0_remove_gravitational_acceleration: false